
services:
  cache:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      - requirepass=eYVX7EwVmmxHLCDmwMtyKV83soLd2t81
      - save='20 1'
    # # --save 20 1 which instructs the server to save 1 or more writes every 20 seconds to disk in case the server restarts
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local